### ISSUE TITLE
HideSidebar: Not light mode compatible.

### ISSUE THREAD

**Issue by TheChilliPL** [Pieloaf/BetterDiscordPlugins#2]
Possible solution:
```css
.hide-sidebar-btn {
  color: var(--interactive-normal);
  background-color: var(--background-secondary);

  transition: background-color .15s ease-out,color .15s ease-out;
}

.hide-sidebar-btn:hover {
  color: #fff;
  background-color: var(--brand-experiment);
}
```
At first, I wanted it to look the same as the original but I thought it may be a better idea to replicate the colors of the Discord button and server icons.
The text color is a bit lighter than the original in dark mode but I'm maybe you could find another variable you could use.
The background color I changed to blue just like the Discord button and servers without explicit icons.
The transition used is the same as the transition on the Discord button and server icons.
The hover color and background color are also the same as on the Discord button and servers.

<details><summary>Comparison</summary>

### Before
![image](https://user-images.githubusercontent.com/18823939/127737752-579ccf18-8e56-4fea-aa10-d9129c5aa1cb.png)
![image](https://user-images.githubusercontent.com/18823939/127738186-ee86c41c-07c1-4832-aee8-11a15ae265bd.png)
### After
![image](https://user-images.githubusercontent.com/18823939/127738148-807d2530-af3e-47ae-acee-a6fabbfc6a98.png)
![image](https://user-images.githubusercontent.com/18823939/127738154-0b4e9521-1488-4668-bf6b-de0c76d27052.png)

### Before
![image](https://user-images.githubusercontent.com/18823939/127737840-d474a6cd-5c15-42b8-8f5b-99c08c831f38.png)
![image](https://user-images.githubusercontent.com/18823939/127738191-300c0116-62af-4a66-86df-9915edb79a4e.png)
### After
![image](https://user-images.githubusercontent.com/18823939/127737837-a2d0072c-2f2f-4b97-80b4-5882526be9fa.png)
![image](https://user-images.githubusercontent.com/18823939/127738129-3de4fdf8-d471-4adb-a7dd-ddae3ce02872.png)
